### ISSUE TITLE
Crashes on Unicode characters

### ISSUE THREAD

**Issue by noudin-ledger** [Toqozz/wired-notify#110]
Running `master` version of wired, I encountered a crash with a notification containing some unicode character.
```
thread '<unnamed>' panicked at 'byte index 19 is not a char boundary; it is inside '🍕' (bytes 17..21) of `Tech Team 🍻 & 🍕`', library/core/src/str/mod.rs:127:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::str::slice_error_fail_rt
   3: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
   4: core::intrinsics::const_eval_select
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/intrinsics.rs:2696:5
   5: core::str::slice_error_fail
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/str/mod.rs:86:9
   6: wired::maths_utility::escape_decode
   7: <wired::bus::dbus::Notify as wired::bus::dbus_codegen::OrgFreedesktopNotifications>::notify
   8: dbus_crossroads::context::Context::check
   9: dbus_crossroads::ifacedesc::IfaceBuilder<T>::method_with_cr::{{closure}}
  10: dbus_crossroads::crossroads::Crossroads::handle_message_inner
  11: dbus_crossroads::crossroads::Crossroads::handle_message
  12: wired::bus::dbus::init_dbus_thread::{{closure}}
  13: dbus::blocking::Connection::process
  14: wired::bus::dbus::process_dbus
```

This is reproducible with `notify-send "Tech Team 🍻 & 🍕"`

This does not reproduce using only the `🍕` character though.

**Comment by lukelex** [comment]
Now I feel like I'm in the wrong Tech Team...😅

**Comment by noudin-ledger** [comment]
Small analysis: I have the feeling the `escape_decode` is trying to do too much, as `notify-send "& 🍕"` makes it crash.
I'll try to understand and give a fix for this.

**Comment by Toqozz** [comment]
Oh wow, that's not good.  I'd guess this happens when one of the unicode bytes overlaps with one of the ascii bytes that we're checking for: `<>&"'`.

**Comment by noudin-ledger** [comment]
Yes, I have a patch incoming soon!

**Comment by Toqozz** [comment]
This should be fixed in latest master.
